# Generated by Django 5.2.17 on 2026-08-27 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='plan',
            field=models.CharField(choices=[('FREE', 'Free'), ('MOBILE', 'Mobile - ₹149'), ('BASIC', 'Basic - ₹199'), ('STANDARD', 'Standard - ₹499'), ('PREMIUM', 'Premium - ₹649')], default='FREE', max_length=20),
        ),
    ]
